//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gs.engines {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserSettingTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserSettingTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gsGCode.engine.translations.UserSettingTranslations", typeof(UserSettingTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BedSizeXMM_Description {
            get {
                return ResourceManager.GetString("BedSizeXMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (mm).
        /// </summary>
        internal static string BedSizeXMM_Name {
            get {
                return ResourceManager.GetString("BedSizeXMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BedSizeYMM_Description {
            get {
                return ResourceManager.GetString("BedSizeYMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth (mm).
        /// </summary>
        internal static string BedSizeYMM_Name {
            get {
                return ResourceManager.GetString("BedSizeYMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BridgeExtrudeSpeedX_Description {
            get {
                return ResourceManager.GetString("BridgeExtrudeSpeedX.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Extrusion Speed (%).
        /// </summary>
        internal static string BridgeExtrudeSpeedX_Name {
            get {
                return ResourceManager.GetString("BridgeExtrudeSpeedX.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BridgeFillNozzleDiamStepX_Description {
            get {
                return ResourceManager.GetString("BridgeFillNozzleDiamStepX.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Fill Spacing (%).
        /// </summary>
        internal static string BridgeFillNozzleDiamStepX_Name {
            get {
                return ResourceManager.GetString("BridgeFillNozzleDiamStepX.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BridgeVolumeScale_Description {
            get {
                return ResourceManager.GetString("BridgeVolumeScale.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Volume (%).
        /// </summary>
        internal static string BridgeVolumeScale_Name {
            get {
                return ResourceManager.GetString("BridgeVolumeScale.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CarefulExtrudeSpeed_Description {
            get {
                return ResourceManager.GetString("CarefulExtrudeSpeed.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed (mm/s).
        /// </summary>
        internal static string CarefulExtrudeSpeed_Name {
            get {
                return ResourceManager.GetString("CarefulExtrudeSpeed.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Class_Description {
            get {
                return ResourceManager.GetString("Class.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string Class_Name {
            get {
                return ResourceManager.GetString("Class.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ClassTypeName_Description {
            get {
                return ResourceManager.GetString("ClassTypeName.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Type Name.
        /// </summary>
        internal static string ClassTypeName_Name {
            get {
                return ResourceManager.GetString("ClassTypeName.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ClipSelfOverlaps_Description {
            get {
                return ResourceManager.GetString("ClipSelfOverlaps.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Overlapping Perimeters.
        /// </summary>
        internal static string ClipSelfOverlaps_Name {
            get {
                return ResourceManager.GetString("ClipSelfOverlaps.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnableAutoBedLeveling_Description {
            get {
                return ResourceManager.GetString("EnableAutoBedLeveling.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Bed Leveling.
        /// </summary>
        internal static string EnableAutoBedLeveling_Name {
            get {
                return ResourceManager.GetString("EnableAutoBedLeveling.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnableBridging_Description {
            get {
                return ResourceManager.GetString("EnableBridging.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridging.
        /// </summary>
        internal static string EnableBridging_Name {
            get {
                return ResourceManager.GetString("EnableBridging.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnableSupportReleaseOpt_Description {
            get {
                return ResourceManager.GetString("EnableSupportReleaseOpt.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Optimization.
        /// </summary>
        internal static string EnableSupportReleaseOpt_Name {
            get {
                return ResourceManager.GetString("EnableSupportReleaseOpt.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnableSupportShell_Description {
            get {
                return ResourceManager.GetString("EnableSupportShell.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Shell.
        /// </summary>
        internal static string EnableSupportShell_Name {
            get {
                return ResourceManager.GetString("EnableSupportShell.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExtruderTempC_Description {
            get {
                return ResourceManager.GetString("ExtruderTempC.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrusion Temperature (°C).
        /// </summary>
        internal static string ExtruderTempC_Name {
            get {
                return ResourceManager.GetString("ExtruderTempC.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FilamentDiamMM_Description {
            get {
                return ResourceManager.GetString("FilamentDiamMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filament Diameter (mm).
        /// </summary>
        internal static string FilamentDiamMM_Name {
            get {
                return ResourceManager.GetString("FilamentDiamMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FloorLayers_Description {
            get {
                return ResourceManager.GetString("FloorLayers.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Layers.
        /// </summary>
        internal static string FloorLayers_Name {
            get {
                return ResourceManager.GetString("FloorLayers.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GenerateSupport_Description {
            get {
                return ResourceManager.GetString("GenerateSupport.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string GenerateSupport_Name {
            get {
                return ResourceManager.GetString("GenerateSupport.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string GroupAdvanced {
            get {
                return ResourceManager.GetString("GroupAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string GroupBasic {
            get {
                return ResourceManager.GetString("GroupBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridging.
        /// </summary>
        internal static string GroupBridging {
            get {
                return ResourceManager.GetString("GroupBridging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capabilities.
        /// </summary>
        internal static string GroupCapabilities {
            get {
                return ResourceManager.GetString("GroupCapabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extruder.
        /// </summary>
        internal static string GroupExtruder {
            get {
                return ResourceManager.GetString("GroupExtruder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Layer.
        /// </summary>
        internal static string GroupFirstLayer {
            get {
                return ResourceManager.GetString("GroupFirstLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heated Bed.
        /// </summary>
        internal static string GroupHeatedBed {
            get {
                return ResourceManager.GetString("GroupHeatedBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string GroupHidden {
            get {
                return ResourceManager.GetString("GroupHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make &amp; Model.
        /// </summary>
        internal static string GroupIdentifiers {
            get {
                return ResourceManager.GetString("GroupIdentifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string GroupMiscellaneous {
            get {
                return ResourceManager.GetString("GroupMiscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeters.
        /// </summary>
        internal static string GroupPerimeters {
            get {
                return ResourceManager.GetString("GroupPerimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Volume.
        /// </summary>
        internal static string GroupPrintVolume {
            get {
                return ResourceManager.GetString("GroupPrintVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retraction.
        /// </summary>
        internal static string GroupRetraction {
            get {
                return ResourceManager.GetString("GroupRetraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Fill.
        /// </summary>
        internal static string GroupSolidFill {
            get {
                return ResourceManager.GetString("GroupSolidFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparse Fill.
        /// </summary>
        internal static string GroupSparseFill {
            get {
                return ResourceManager.GetString("GroupSparseFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeds.
        /// </summary>
        internal static string GroupSpeeds {
            get {
                return ResourceManager.GetString("GroupSpeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string GroupSupport {
            get {
                return ResourceManager.GetString("GroupSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string GroupTemperature {
            get {
                return ResourceManager.GetString("GroupTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HasAutoBedLeveling_Description {
            get {
                return ResourceManager.GetString("HasAutoBedLeveling.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Bed Leveling.
        /// </summary>
        internal static string HasAutoBedLeveling_Name {
            get {
                return ResourceManager.GetString("HasAutoBedLeveling.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HasHeatedBed_Description {
            get {
                return ResourceManager.GetString("HasHeatedBed.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Heated Bed.
        /// </summary>
        internal static string HasHeatedBed_Name {
            get {
                return ResourceManager.GetString("HasHeatedBed.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HeatedBedTempC_Description {
            get {
                return ResourceManager.GetString("HeatedBedTempC.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed Temperature (°C).
        /// </summary>
        internal static string HeatedBedTempC_Name {
            get {
                return ResourceManager.GetString("HeatedBedTempC.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Identifier_Description {
            get {
                return ResourceManager.GetString("Identifier.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string Identifier_Name {
            get {
                return ResourceManager.GetString("Identifier.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InteriorSolidRegionShells_Description {
            get {
                return ResourceManager.GetString("InteriorSolidRegionShells.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Fill Interior Shells.
        /// </summary>
        internal static string InteriorSolidRegionShells_Name {
            get {
                return ResourceManager.GetString("InteriorSolidRegionShells.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LayerHeightMM_Description {
            get {
                return ResourceManager.GetString("LayerHeightMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Height (mm).
        /// </summary>
        internal static string LayerHeightMM_Name {
            get {
                return ResourceManager.GetString("LayerHeightMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ManufacturerName_Description {
            get {
                return ResourceManager.GetString("ManufacturerName.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Name.
        /// </summary>
        internal static string ManufacturerName_Name {
            get {
                return ResourceManager.GetString("ManufacturerName.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ManufacturerUUID_Description {
            get {
                return ResourceManager.GetString("ManufacturerUUID.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer UUID.
        /// </summary>
        internal static string ManufacturerUUID_Name {
            get {
                return ResourceManager.GetString("ManufacturerUUID.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MaxBedTempC_Description {
            get {
                return ResourceManager.GetString("MaxBedTempC.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Bed Temperature (°C).
        /// </summary>
        internal static string MaxBedTempC_Name {
            get {
                return ResourceManager.GetString("MaxBedTempC.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MaxBridgeWidthMM_Description {
            get {
                return ResourceManager.GetString("MaxBridgeWidthMM_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Bridge Distance (mm).
        /// </summary>
        internal static string MaxBridgeWidthMM_Name {
            get {
                return ResourceManager.GetString("MaxBridgeWidthMM_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MaxExtruderTempC_Description {
            get {
                return ResourceManager.GetString("MaxExtruderTempC.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Extruder Temperature (°C).
        /// </summary>
        internal static string MaxExtruderTempC_Name {
            get {
                return ResourceManager.GetString("MaxExtruderTempC.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MaxExtrudeSpeedMMM_Description {
            get {
                return ResourceManager.GetString("MaxExtrudeSpeedMMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Extrusion Speed (mm/s).
        /// </summary>
        internal static string MaxExtrudeSpeedMMM_Name {
            get {
                return ResourceManager.GetString("MaxExtrudeSpeedMMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MaxHeightMM_Description {
            get {
                return ResourceManager.GetString("MaxHeightMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (mm).
        /// </summary>
        internal static string MaxHeightMM_Name {
            get {
                return ResourceManager.GetString("MaxHeightMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MaxLayerHeightMM_Description {
            get {
                return ResourceManager.GetString("MaxLayerHeightMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Layer Height (mm).
        /// </summary>
        internal static string MaxLayerHeightMM_Name {
            get {
                return ResourceManager.GetString("MaxLayerHeightMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MaxRetractSpeedMMM_Description {
            get {
                return ResourceManager.GetString("MaxRetractSpeedMMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Retraction Speed (mm/s).
        /// </summary>
        internal static string MaxRetractSpeedMMM_Name {
            get {
                return ResourceManager.GetString("MaxRetractSpeedMMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MaxTravelSpeedMMM_Description {
            get {
                return ResourceManager.GetString("MaxTravelSpeedMMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum X/Y Travel Speed (mm/s).
        /// </summary>
        internal static string MaxTravelSpeedMMM_Name {
            get {
                return ResourceManager.GetString("MaxTravelSpeedMMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MaxZTravelSpeedMMM_Description {
            get {
                return ResourceManager.GetString("MaxZTravelSpeedMMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Z Travel Speed (mm/s).
        /// </summary>
        internal static string MaxZTravelSpeedMMM_Name {
            get {
                return ResourceManager.GetString("MaxZTravelSpeedMMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MinBedTempC_Description {
            get {
                return ResourceManager.GetString("MinBedTempC.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Bed Temperature (°C).
        /// </summary>
        internal static string MinBedTempC_Name {
            get {
                return ResourceManager.GetString("MinBedTempC.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MinExtruderTempC_Description {
            get {
                return ResourceManager.GetString("MinExtruderTempC.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Extruder Temperature (°C).
        /// </summary>
        internal static string MinExtruderTempC_Name {
            get {
                return ResourceManager.GetString("MinExtruderTempC.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MinExtrudeSpeed_Description {
            get {
                return ResourceManager.GetString("MinExtrudeSpeed.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Extrusion Speed (mm/s).
        /// </summary>
        internal static string MinExtrudeSpeed_Name {
            get {
                return ResourceManager.GetString("MinExtrudeSpeed.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MinLayerHeightMM_Description {
            get {
                return ResourceManager.GetString("MinLayerHeightMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Layer Height (mm).
        /// </summary>
        internal static string MinLayerHeightMM_Name {
            get {
                return ResourceManager.GetString("MinLayerHeightMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MinLayerTime_Description {
            get {
                return ResourceManager.GetString("MinLayerTime.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Layer Time (s).
        /// </summary>
        internal static string MinLayerTime_Name {
            get {
                return ResourceManager.GetString("MinLayerTime.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MinPointSpacingMM_Description {
            get {
                return ResourceManager.GetString("MinPointSpacingMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Point Spacing (mm).
        /// </summary>
        internal static string MinPointSpacingMM_Name {
            get {
                return ResourceManager.GetString("MinPointSpacingMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MinRetractTravelLength_Description {
            get {
                return ResourceManager.GetString("MinRetractTravelLength.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Retraction Threshold (mm).
        /// </summary>
        internal static string MinRetractTravelLength_Name {
            get {
                return ResourceManager.GetString("MinRetractTravelLength.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ModelEnum_Description {
            get {
                return ResourceManager.GetString("ModelEnum.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Enum.
        /// </summary>
        internal static string ModelEnum_Name {
            get {
                return ResourceManager.GetString("ModelEnum.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ModelIdentifier_Description {
            get {
                return ResourceManager.GetString("ModelIdentifier.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Identifier.
        /// </summary>
        internal static string ModelIdentifier_Name {
            get {
                return ResourceManager.GetString("ModelIdentifier.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ModelUUID_Description {
            get {
                return ResourceManager.GetString("ModelUUID.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model UUID.
        /// </summary>
        internal static string ModelUUID_Name {
            get {
                return ResourceManager.GetString("ModelUUID.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NozzleDiamMM_Description {
            get {
                return ResourceManager.GetString("NozzleDiamMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nozzle Diameter (mm).
        /// </summary>
        internal static string NozzleDiamMM_Name {
            get {
                return ResourceManager.GetString("NozzleDiamMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OuterPerimeterSpeedX_Description {
            get {
                return ResourceManager.GetString("OuterPerimeterSpeedX.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior Perimeter Speed (%).
        /// </summary>
        internal static string OuterPerimeterSpeedX_Name {
            get {
                return ResourceManager.GetString("OuterPerimeterSpeedX.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OuterShellLast_Description {
            get {
                return ResourceManager.GetString("OuterShellLast.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior Perimeter Last.
        /// </summary>
        internal static string OuterShellLast_Name {
            get {
                return ResourceManager.GetString("OuterShellLast.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RapidExtrudeSpeed_Description {
            get {
                return ResourceManager.GetString("RapidExtrudeSpeed.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (mm/s).
        /// </summary>
        internal static string RapidExtrudeSpeed_Name {
            get {
                return ResourceManager.GetString("RapidExtrudeSpeed.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RapidTravelSpeed_Description {
            get {
                return ResourceManager.GetString("RapidTravelSpeed.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel (mm/s).
        /// </summary>
        internal static string RapidTravelSpeed_Name {
            get {
                return ResourceManager.GetString("RapidTravelSpeed.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RetractDistanceMM_Description {
            get {
                return ResourceManager.GetString("RetractDistanceMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retraction Amount (mm).
        /// </summary>
        internal static string RetractDistanceMM_Name {
            get {
                return ResourceManager.GetString("RetractDistanceMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RetractSpeed_Description {
            get {
                return ResourceManager.GetString("RetractSpeed.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retraction Speed (mm/s).
        /// </summary>
        internal static string RetractSpeed_Name {
            get {
                return ResourceManager.GetString("RetractSpeed.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RoofLayers_Description {
            get {
                return ResourceManager.GetString("RoofLayers.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roof Layers.
        /// </summary>
        internal static string RoofLayers_Name {
            get {
                return ResourceManager.GetString("RoofLayers.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SelfOverlapToleranceX_Description {
            get {
                return ResourceManager.GetString("SelfOverlapToleranceX.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Overlapping Perimeters Tolerance.
        /// </summary>
        internal static string SelfOverlapToleranceX_Name {
            get {
                return ResourceManager.GetString("SelfOverlapToleranceX.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Shells_Description {
            get {
                return ResourceManager.GetString("Shells.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeters.
        /// </summary>
        internal static string Shells_Name {
            get {
                return ResourceManager.GetString("Shells.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ShellsFillNozzleDiamStepX_Description {
            get {
                return ResourceManager.GetString("ShellsFillNozzleDiamStepX.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter Spacing (%).
        /// </summary>
        internal static string ShellsFillNozzleDiamStepX_Name {
            get {
                return ResourceManager.GetString("ShellsFillNozzleDiamStepX.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolidFillBorderOverlapX_Description {
            get {
                return ResourceManager.GetString("SolidFillBorderOverlapX.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Fill to Perimeter Overlap (%).
        /// </summary>
        internal static string SolidFillBorderOverlapX_Name {
            get {
                return ResourceManager.GetString("SolidFillBorderOverlapX.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolidFillNozzleDiamStepX_Description {
            get {
                return ResourceManager.GetString("SolidFillNozzleDiamStepX.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Fill Spacing (%).
        /// </summary>
        internal static string SolidFillNozzleDiamStepX_Name {
            get {
                return ResourceManager.GetString("SolidFillNozzleDiamStepX.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SparseFillBorderOverlapX_Description {
            get {
                return ResourceManager.GetString("SparseFillBorderOverlapX.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparse Fill to Perimeter Overlap (%).
        /// </summary>
        internal static string SparseFillBorderOverlapX_Name {
            get {
                return ResourceManager.GetString("SparseFillBorderOverlapX.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SparseLinearInfillStepX_Description {
            get {
                return ResourceManager.GetString("SparseLinearInfillStepX.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparse Fill Spacing (%).
        /// </summary>
        internal static string SparseLinearInfillStepX_Name {
            get {
                return ResourceManager.GetString("SparseLinearInfillStepX.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StartLayerHeightMM_Description {
            get {
                return ResourceManager.GetString("StartLayerHeightMM.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Height (mm).
        /// </summary>
        internal static string StartLayerHeightMM_Name {
            get {
                return ResourceManager.GetString("StartLayerHeightMM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StartLayers_Description {
            get {
                return ResourceManager.GetString("StartLayers.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string StartLayers_Name {
            get {
                return ResourceManager.GetString("StartLayers.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SupportAreaOffsetX_Description {
            get {
                return ResourceManager.GetString("SupportAreaOffsetX.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Offset (%).
        /// </summary>
        internal static string SupportAreaOffsetX_Name {
            get {
                return ResourceManager.GetString("SupportAreaOffsetX.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SupportMinZTips_Description {
            get {
                return ResourceManager.GetString("SupportMinZTips.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Z Tips.
        /// </summary>
        internal static string SupportMinZTips_Name {
            get {
                return ResourceManager.GetString("SupportMinZTips.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SupportOverhangAngleDeg_Description {
            get {
                return ResourceManager.GetString("SupportOverhangAngleDeg.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overhang Threshold (deg).
        /// </summary>
        internal static string SupportOverhangAngleDeg_Name {
            get {
                return ResourceManager.GetString("SupportOverhangAngleDeg.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SupportPointDiam_Description {
            get {
                return ResourceManager.GetString("SupportPointDiam.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Tip Diameter (mm).
        /// </summary>
        internal static string SupportPointDiam_Name {
            get {
                return ResourceManager.GetString("SupportPointDiam.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SupportPointSides_Description {
            get {
                return ResourceManager.GetString("SupportPointSides.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Tip Sides.
        /// </summary>
        internal static string SupportPointSides_Name {
            get {
                return ResourceManager.GetString("SupportPointSides.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SupportRegionJoinTolX_Description {
            get {
                return ResourceManager.GetString("SupportRegionJoinTolX.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Merge Tolerance (%).
        /// </summary>
        internal static string SupportRegionJoinTolX_Name {
            get {
                return ResourceManager.GetString("SupportRegionJoinTolX.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SupportReleaseGap_Description {
            get {
                return ResourceManager.GetString("SupportReleaseGap.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Z-Gap (mm).
        /// </summary>
        internal static string SupportReleaseGap_Name {
            get {
                return ResourceManager.GetString("SupportReleaseGap.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SupportSolidSpace_Description {
            get {
                return ResourceManager.GetString("SupportSolidSpace.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Space.
        /// </summary>
        internal static string SupportSolidSpace_Name {
            get {
                return ResourceManager.GetString("SupportSolidSpace.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SupportSpacingStepX_Description {
            get {
                return ResourceManager.GetString("SupportSpacingStepX.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Spacing (%).
        /// </summary>
        internal static string SupportSpacingStepX_Name {
            get {
                return ResourceManager.GetString("SupportSpacingStepX.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SupportVolumeScale_Description {
            get {
                return ResourceManager.GetString("SupportVolumeScale.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Scale (%).
        /// </summary>
        internal static string SupportVolumeScale_Name {
            get {
                return ResourceManager.GetString("SupportVolumeScale.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ZTravelSpeed_Description {
            get {
                return ResourceManager.GetString("ZTravelSpeed.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Travel Speed (mm/s).
        /// </summary>
        internal static string ZTravelSpeed_Name {
            get {
                return ResourceManager.GetString("ZTravelSpeed.Name", resourceCulture);
            }
        }
    }
}
